version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Remove the deploy section above if you don't have NVIDIA GPU

  ai-recruitment-app:
    build: .
    container_name: ai-recruitment-app
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - DEBUG=false
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
